#!/bin/bash
# This hook is run after every virtualenv is activated.

proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
if [ -d ~/projects/$proj_name ]; then
    cd ~/projects/$proj_name
fi
export PS1="\n$PS1"
